baseURL = 'https://cringe.live/'
languageCode = 'en-us'
title = 'cringe.live'
theme = "theme"
paginate = 10

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

[permalinks]
  posts = '/:year/:month/:title/'

[outputs]
  home = ['html', 'rss']

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  author = "Balazs Horvath"
  description = "Just doing what the machines told me to.."
  keywords = "nerdy stuff, blog, powershell, python, machine learning"
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  
[languages]
  [languages.en.params]
    title = "Unbound Epochs"
    subtitle = "Just doing what the machines told me to.."
    keywords = "nerdy stuff, blog,"
    copyright = "Balazs Horvath"
    email = "acsipont@gmail.com"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "These are relevant somehow"

    [languages.en.params.logo]
      logoText = "cringe.live"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
          identifier = "blog"
          name = "Blog"
          url = "/blog"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
